services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - .:/docker-entrypoint-initdb.d
      - migrator-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user_migrate"
      POSTGRES_PASSWORD: "pass_migrate"  
      PGDATA: "/var/lib/postgresql/data/pgdata"

volumes:
  migrator-data:
