# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOLANG_VERSION: ~1.23
  GOLANGCI_LINT_VERSION: v1.63.4

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s ${{ env.GOLANGCI_LINT_VERSION }}
        sudo mv ./bin/golangci-lint /usr/local/bin/

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Run tests with coverage
      run: go test -race -count 100 ./...

    - name: Codecov
      uses: codecov/codecov-action@v5.4.2

    - name: Build
      run: go build -v ./...
       
